# Generated by Django 3.0.6 on 2020-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ash_tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='artists',
            name='Email_id',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='artists',
            name='First_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='artists',
            name='Last_name',
            field=models.CharField(max_length=30),
        ),
    ]
